services:
  react-app:
    build: .
    container_name: convocatorias_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - "scandb.sspc.gob.mx:192.168.46.48"